name: kueski-ds
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - lightgbm
  - seaborn
  - matplotlib
  - tqdm
